name: "mostlycurious"
description: "blog"

url: "http://rpjb.github.com"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: false

prose:
  siteurl: "http://mostlycurious.com"
  media: "img/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          label: "author"
          value: "robert barretto"
      - name: "image"
        field:
          element: "text"
          label: "image"
          value: ""
