name: "mostlycurious"
description: "blog"

url: "http://rpjb.github.com"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: false

prose:
  rooturl: '_posts'
  siteurl: 'http://rpjb.github.com'
  relativeLinks: 'http://rpjb.github.com/links.jsonp'
  media: 'media'
	metadata:
      source/_posts:
      	- name: "layout"
          field:
            element: "hidden"
            value: "post"
        - name: "title"
          field:
            element: "text"
            label: "Title"
            value: ""
            type: "text"
        - name: "author"
          field:
            element: "text"
            label: "Author"
            value: ""
            placeholder: "Trunk Botterson"
            type: "text"
        - name: "tags"
          field:
            element: "multiselect"
            label: "Add Tags"
            placeholder: "Choose Tags"
            alterable: true

        	
    