name: "mostlycurious"
description: "blog"

url: "http://rpjb.github.com"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: false

prose:
  siteurl: "http://mostlycurious.com"
  media: "img/posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
	  - name: "author"
        field:
          element: "text"
          label: "Author"
          value: "a"
          type: "text"